deployment: 
  tasks: 
    - export DEPLOYPATH=/home/jdanield/repositories/Guitar-LA 
    - TARGET_PATH=/home/jdanield/public_html/guitarla 
    - /usr/bin/git -c $DEPLOY_PATH reset --hard 
    - /usr/bin/git $DEPLOY_PATH pull origin main 
    - echo "Despliegue completo en $(date)" >> $DEPLOY_PATH/deploy.log