deployment:
  tasks:
    - cd /home/jdanield/repositories/Guitar-LA
    - git reset --hard
    - git pull origin main
    - npm install
    - npm run build
    - mkdir -p /home/jdanield/public_html/guitarla
    - rsync -av --delete /home/jdanield/repositories/Guitar-LA/dist/ /home/jdanield/public_html/guitarla/
    - echo "Despliegue completo en $(date)" >> /home/jdanield/repositories/Guitar-LA/deploy.log
